# Generated by Django 6.1.1 on 2026-09-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_alter_tag_options_alter_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="todo.tag"
            ),
        ),
    ]
